window.siteContent = {
  en: {
    marquee: "artist, graphic designer, full-stack developer,",
    bioParagraphs: [
      "Jakub Kanna (formally Jakub Trzciński) is a Polish interdisciplinary artist born in 1996 in Mrągowo. His early years were shaped by intensive sport education, a discipline that later evolved into a practice grounded in endurance, experimentation, and the experience of risk.",
      "Kanna studied at the Academy of Fine Arts in Prague (2022) and holds a BA in Printmaking and an MA in Intermedia from the University of the Arts in Poznań. In 2024, he completed a full-stack developer course at TOP, expanding his work into the intersections of art, technology, and hybrid media.",
      [
        "His most notable projects include ",
        '<a href="https://archive.jakubkanna.com/works?tags=Velo-art" target="_blank" rel="noreferrer noopener">Velo-art</a> ',
        "and ",
        '<a href="https://archive.jakubkanna.com/works?tags=Fight+or+Flight" target="_blank" rel="noreferrer noopener">Fight or Flight</a>, ',
        "exploring relationships between culture, the human FFF response, and symbolic abstraction.",
      ].join(""),
      [
        "Jakub's works have been presented, among others, at ",
        '<a href="https://prog.wrocenter.pl/en/" target="_blank" rel="noreferrer noopener">WRO Art Center</a>, ',
        '<a href="https://artmuseum.pl/en" target="_blank" rel="noreferrer noopener">Muzeum Sztuki Nowoczesnej in Warsaw</a>, ',
        '<a href="https://ptt-poznan.pl/en/" target="_blank" rel="noreferrer noopener">Polish Dance Theater</a> ',
        "and on ",
        '<a href="https://newscenario.net" target="_blank" rel="noreferrer noopener">newscenario.net</a>. ',
        "He took part in residencies and workshops at the ",
        '<a href="https://rzezba-oronsko.pl" target="_blank" rel="noreferrer noopener">Centre of Polish Sculpture in Orońsko</a> ',
        "and the ",
        '<a href="https://www.instagram.com/w788km/" target="_blank" rel="noreferrer noopener">W788 Foundation</a>, ',
        "and also published in ",
        '<a href="https://artmuseum.pl/en" target="_blank" rel="noreferrer noopener">Adres Prywatny (MSN)</a> ',
        "and in ",
        '<a href="https://czaskultury.pl/artykuly/secret-life-of-a-thing/" target="_blank" rel="noreferrer noopener">Czas Kultury</a>.',
        "<br/>",
        "<br/>",
        'A new project: <a href="https://artbubble.in" target="_blank" rel="noreferrer noopener">ArtBubble</a>',
      ].join(""),
    ],
    readMore: "Read more",
    readLess: "Read less",
  },
  pl: {
    marquee: "artysta, grafik, full-stack developer,",
    bioParagraphs: [
      "Jakub Kanna (formalnie Jakub Trzciński) to polski artysta interdyscyplinarny urodzony w 1996 roku w Mrągowie. Jego wczesne lata wypełniła intensywna edukacja sportowa, która później przerodziła się w praktykę opartą na wytrzymałości, eksperymencie i doświadczaniu ryzyka.",
      "Studiował na Akademii Sztuk Pięknych w Pradze (2022) oraz ukończył grafikę (BA) i intermedia (MA) na Uniwersytecie Artystycznym w Poznaniu. W 2024 roku ukończył kurs full-stack developera w TOP, rozszerzając pracę o przecięcia sztuki, technologii i mediów hybrydowych.",
      [
        "Do jego najważniejszych projektów należą ",
        '<a href="https://archive.jakubkanna.com/works?tags=Velo-art" target="_blank" rel="noreferrer noopener">Velo-art</a> ',
        "i ",
        '<a href="https://archive.jakubkanna.com/works?tags=Fight+or+Flight" target="_blank" rel="noreferrer noopener">Fight or Flight</a>, ',
        "badające zależności między kulturą, reakcją FFF człowieka i symboliczną abstrakcją.",
      ].join(""),
      [
        "Prace Jakuba były prezentowane m.in. w ",
        '<a href="https://prog.wrocenter.pl/en/" target="_blank" rel="noreferrer noopener">WRO Art Center</a>, ',
        '<a href="https://artmuseum.pl/en" target="_blank" rel="noreferrer noopener">Muzeum Sztuki Nowoczesnej w Warszawie</a>, ',
        '<a href="https://ptt-poznan.pl/en/" target="_blank" rel="noreferrer noopener">Polskim Teatrze Tańca</a> ',
        "oraz na ",
        '<a href="https://newscenario.net" target="_blank" rel="noreferrer noopener">newscenario.net</a>. ',
        "Brał udział w rezydencjach i warsztatach w ",
        '<a href="https://rzezba-oronsko.pl" target="_blank" rel="noreferrer noopener">Centrum Rzeźby Polskiej w Orońsku</a> ',
        "oraz w ",
        '<a href="https://www.instagram.com/w788km/" target="_blank" rel="noreferrer noopener">Fundacji W788</a>, ',
        "a także publikował w ",
        '<a href="https://artmuseum.pl/en" target="_blank" rel="noreferrer noopener">Adresie Prywatnym (MSN)</a> ',
        "i w ",
        '<a href="https://czaskultury.pl/artykuly/secret-life-of-a-thing/" target="_blank" rel="noreferrer noopener">Czasie Kultury</a>.',
        "<br/>",
        "<br/>",
        'Nowy projekt: <a href="https://artbubble.in" target="_blank"> ArtBubble</a>',
      ].join(""),
    ],
    readMore: "Czytaj więcej",
    readLess: "Czytaj mniej",
  },
};
